### PR TITLE
Cleanup of net headers

### PR DESCRIPTION
**Pull request by dee12452**
Addresses #5. Moved socket, poll, select to sys. Put lv2 sysNet functions in their own header in sysutil. Moved netdb.h to root of include/. Added ppu/include/sys to LIBPSL1GHT_INC in ppu_rules.

### CODE REVIEW

**Comment by dee12452** [comment]
Attempting to build the changes using docker + ps3toolchain/Dockerfile. Can get past 008-psl1ght.sh but hitting
```
checking whether the C compiler works... no
configure: error: in `/build/build/ps3libraries/build/libpng-1.4.4/build-ppu':
configure: error: C compiler cannot create executables
See `config.log' for more details.
../scripts/002-libpng-1.4.4.sh: Failed.
../scripts/009-ps3libraries.sh: Failed.
The command '/bin/sh -c /build/toolchain.sh' returned a non-zero code: 1
```
which was reported herehttps://github.com/ps3dev/ps3toolchain/issues/94. I'll try a different system so I can see the config.log

**Comment by miigotu** [comment]
That dockerfile is not finished. Build the toolchain locally or use the submodules branch for a dockerfile that should work.

**Comment by dee12452** [comment]
@miigotu Cool I'll give that a shot

**Comment by dee12452** [comment]
Closing: accidentally included a commit from master not yet in develop

**Pull request closed without merging**
