### PR TITLE
IF UNAME must be system indipendent

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by shagkur** [comment]
Is 'bash' not available under mingw/cygwin? Using regex patterns like in the comment of #92 should work too? At least it does for *nix.

**Comment by bucanero** [comment]
btw, line 24 might bring the same issue (`[[...]]`):
```bash
if [[ $CGHASH =~ "28f6073b" || $CGHASH =~ "e5228ec2" ]];
```

**Comment by crystalct** [comment]
If you are there you are cywin or mingw user.....

**Comment by zeldin** [comment]
Isn' t the whole point of `uname` to _not_ be system independent?  :wink:

If all you need is a glob pattern you can use `case` instead of `if`, this should work in any bourne-like shell.

**Comment by crystalct** [comment]
It should be a SH script..... are there cygwin or mingw installations without sh?

**Comment by shagkur** [comment]
> Isn' t the whole point of `uname` to _not_ be system independent? 
> 
> If all you need is a glob pattern you can use `case` instead of `if`, this should work in any bourne-like shell.

Yes, that's probably the best apporach. So does the 'configure' script at many places.

**Comment by shagkur** [comment]
> It should be a SH script..... are there cygwin or mingw installations without sh?

Like @zeldin wrote, a `case` instead of `if` should do the trick for POSIX shell aswell (as configure does)

**Comment by shagkur** [comment]
> > It should be a SH script..... are there cygwin or mingw installations without sh?
> 
> Like @zeldin wrote, a `case` instead of `if` should do the trick for POSIX shell aswell (as configure does)

**Comment by shagkur** [comment]
Sorry didn't want to close it.

**Comment by crystalct** [comment]
> > > It should be a SH script..... are there cygwin or mingw installations without sh?
> 
> Like @zeldin wrote, a `case` instead of `if` should do the trick for POSIX shell aswell (as configure does)
> The proposed script in the other thread was just a quick fix of mine done on a *nix env.

Where is that script?

**Comment by crystalct** [comment]
LOL... i'm blind

**Comment by bucanero** [comment]
> Where is that script?

@shagkur posted it in a comment in the #92 thread, but I think the auto-formatting of Github messed up with it. 😞 

Here's what a snippet:
```bash
UNAME=$(uname -a)

if [[ "$UNAME" =~ (CYGWIN|MINGW) ]];
then
## Download a fresh cg.dll
rm -f cg.zip;
rm -f cg.dll;
if [[ "$UNAME" =~ (x86_64|MINGW64) ]];
then
wget --continue --no-check-certificate https://wikidll.com/download/3726/cg.zip;
else
wget --continue --no-check-certificate https://wikidll.com/download/3730/cg.zip;
fi

## Install cg.dll
echo "Installing cg.dll in $PS3DEV/bin"
unzip cg.zip
rm -f cg.zip
CGHASH=$(rhash -C cg.dll -p "%{crc32}") 
if [[ "$CGHASH" =~ (28f6073b|e5228ec2) ]];
then
	chmod 766 cg.dll
	mv -f cg.dll $PS3DEV/bin;
else
	echo "Error - cg.dll: wrong CRC32";
fi
fi
```

**Comment by crystalct** [comment]
```
root@6e0b3053f9c3:/root/PSL1GHT/tools/cgcomp# uname -a
Linux 6e0b3053f9c3 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@6e0b3053f9c3:/root/PSL1GHT/tools/cgcomp# ./cgdll-installer.sh
./cgdll-installer.sh: 7: ./cgdll-installer.sh: Syntax error: "(" unexpected (expecting "then")
root@6e0b3053f9c3:/root/PSL1GHT/tools/cgcomp#
```

**Comment by shagkur** [comment]
Change the header of the script from:
#!/bin/sh -e
to
#!/usr/bin/env bash

That should fix the errors.

crystalct <notifications@github.com> schrieb am Mo. 29. Juni 2020 um 16:25:

**Comment by miigotu** [comment]
I think it should stay sh instead of bash. Mac doesn't have bash it only has sh afaik, at least some versions. This is why the rest of the toolchain uses sh.

You can't use double brackets in sh.

**Comment by crystalct** [comment]
Are "sh", "uname", "if" and "grep" present in every linux, mac, cygwin and mingw system?
Maybe "sh" and if echo $UNAME | grep "CYGWIN" etc etc is more common.....

**Comment by bucanero** [comment]
I think that the operating system conditional logic could be on the Make file, as it’s done for all the other tools already. 

Example:

‘’’
ifneq (,$(findstring MINGW,$(UNAME)))
	POSTFIX	:= .exe
	CFLAGS	+= -mno-cygwin
	LDFLAGS += -mno-cygwin -s -lelf
	OS		:= win32
endif

ifneq (,$(findstring CYGWIN,$(UNAME)))
	POSTFIX	:= .exe
	LDFLAGS += -s -lelf
	OS		:= win32
endif
‘’’

**Pull request merged**
